name: FastAPI AWS Lambda CI/CD

on:
  # Trigger the workflow on push
  jobs:

    CI:
      # Define the runner used in the workflow
      runs-on: ubuntu-latest
      steps:
      # Checks out repo so our workflow can access it
        - uses: actions/checkout@v2

        # Step - 1 Setup Python
        - name: Setup Python
          # This action sets up a Python environment for use in actions
          uses: actions/setup-python@v2
          with:
            python-version: 3.7
            
        # Step - 2 Intall Python virtual env
        - name: Install Python Virtual env
          run: pip3 install virtualenv
        
        # Step - 3 Setup Virtual env
        - name: Virtual env
          uses: actions/cache@v2
          id: cachce-env # for referring name of the caceh later
          with:
            path: venv # What we actually cached: The virtual env file
            # This cache key depends on the requirements.txt
            key: ${{ runner.os }}-venv-${{ hashFiles('**requirements*.txt') }}
            restore-keys: /
              ${{ runner.os }}-venv-

        # Step - 4 Build a Virtual env, but only if it doesn't already exists
        - name: Activate Virtual env
          run: python -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt
          if: steps.cache-env.output.cache-hit != 'true'

        - name: Run Tests
          # Note that you have to activate the virtualenv in every step
          # because Github actions doesn't preserve the environment
          run: . venv/bin/activate && pytest

        - name: Create archive of dependencies
          run: /
            cd ./venv/lib/python3.7/site-packages
            zip -r9 ../../../../api.zip
        - name: Add API files to Zip file
          run: cd ./api && zip -g ../api.zip -r .
        - name: Upload zip file artifact
          # uploads artifacts from your workflow allowing you to share data between jobs
          # Stores data once a workflow is complete
          uses: actions/upload-artifact@v2
          with:
            name: api
            path: api.zip

        